import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionRouter from "./session";
import departmentsRouter from "./departments";
import departmentSettingsRouter from "./departmentSettings";
import boardMembersRouter from "./boardMembers";
import ticketsRouter from "./tickets";
import ticketViewsRouter from "./ticketViews";
import boardViewsRouter from "./boardViews";
import peopleRouter from "./people";
import agentsRouter from "./agents";
import knowledgeBaseRouter from "./knowledgeBase";
import timeEntriesRouter from "./timeEntries";
import assetsRouter from "./assets";
import applicationsRouter from "./applications";
import vendorsRouter from "./vendors";
import projectsRouter from "./projects";
import initiativesRouter from "./initiatives";
import operationalTasksRouter from "./operationalTasks";
import riskRulesRouter from "./riskRules";
import workflowsRouter from "./workflows";
import dashboardRouter from "./dashboard";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sessionRouter);
router.use(departmentsRouter);
router.use(departmentSettingsRouter);
router.use(boardMembersRouter);
router.use(ticketsRouter);
router.use(ticketViewsRouter);
router.use(boardViewsRouter);
router.use(peopleRouter);
router.use(agentsRouter);
router.use(knowledgeBaseRouter);
router.use(timeEntriesRouter);
router.use(assetsRouter);
router.use(applicationsRouter);
router.use(vendorsRouter);
router.use(projectsRouter);
router.use(initiativesRouter);
router.use(operationalTasksRouter);
router.use(riskRulesRouter);
router.use(workflowsRouter);
router.use(dashboardRouter);

export default router;
